### ISSUE TITLE
remove `base-task` dependency?

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/base-task-alias#3]
@jonschlinkert, what's the "best practice" for you. **Should I have required deps and try to load them, or let it throw if not found method?**

For me both make sense, and in anyway you will install these deps that are required by some plugin when it throws.

Somewhere in `base` docs you should add notice like:

> Always install plugins you wanted and load them, using `.use` method in your app, even if they are deps of some other plugin(s).

Just realized this awesomeness of @node-base architecture yesterday.

I'm talking for that if we building some app like this one for example:

``` js
var Base = require('base')

// always add plugins you need, even if they are deps
// of some other plugin
var task = require('base-task')
var taskAlias = require('base-task-alias')
var taskRender = require('base-task-render')
var options= require('base-option')
var watch = require('base-watch')
var fs= require('base-fs')
var conflicts= require('base-fs-conflicts')

function MyApp () {
  Base.call(this, arguments)
  this.use(task())
  this.use(taskAlias())
  this.use(taskRender())
  this.use(watch())
  this.use(options())
  this.use(conflicts())
  this.use(fs())
}
Base.extend(MyApp)

var app = new MyApp()

// my app stuff below
```

and let say `base-task-alias` plugin currently has `base-task` dependency and `base-task-render` requires `assemble-render-file`, `base-fs` and `base-fs-conflicts` for example. 

In this situation user **SHOULD NOT** think _"oh, it seems base-task-alias and base-task-render includes these deps so i will not install them in my project and won't load them"_ - no.

> Always install plugins you wanted and load them, using `.use` method in your app, even if they are deps of some other plugin(s).

This should be noted in @node-base docs as "best practise" , because the awesome loading system of base will use the first loaded plugins. And if he (the user building some app) do it correctly and following this practise and install all of them in his project he will use newer versions of them, not that that are installed by some other plugin.

For example `base-task-alias`'s base-task version is `0.1.1` (for example), if user follows above practise he will install `base-task` the `0.5.0` and load in in his app `app.use(tasks())`, the application and the `base-task-alias` will use the newer version - `0.5.0` not that which `base-task-alias` requires.

Got it? sorry, but i'm not so concetrated now. Ask if you need clarify.

**Comment by tunnckoCore** [comment]
bumped

**Comment by jonschlinkert** [comment]
sorry just saw this. yeah I think that's a good summary of how how plugins are loaded. You should always `require()` in the plugins you need and add them as dependencies to your app. 

Changing subjects... about changing task names, we considered adding an option for renaming tasks at one point, but decided not to because of task dependencies and potential for confusion with them. However, I still think this would be nice to have if it's done correctly. But @doowb would be better to speak to that, since he did most of the task logic, and composer.

**Comment by doowb** [comment]
> changing task names

I think it would be very complicated to try to change a task name (since it can be a dependency of another task and would require all of the tasks to be inspected to determine if the name of the dependency should change).

However, it looks like you're just basically doing... `app.task('alias', [currentTaskName])` so it's just setting the current task as a dependency of the "alias" task.

Also, I understand what you're thinking when you want to remove `base-task` and let a user require that in themselves so they can control the version themselves, but I think that starts causing more problems than it's worth. If that dependency (`base-task` in this case) changes it's api for some reason and a user tries to use the newer api that `base-task-alias` doesn't know about, then you'll start getting issues.

I think it's better to include the dependency in your dependencies and if you get an issue from someone that there's a newer version of `base-task`, you can just bump that along with your version number so everyone can use it.

**Comment by jonschlinkert** [comment]
> I think it's better to include the dependency in your dependencies

that's exactly what I said, but I must have misread what the question was if I implied otherwise. thx

**Comment by tunnckoCore** [comment]
@doowb agree.

Rethinking now and it make more sense to save it as dependency, yea. Thanks. :)
